----------------------------------------------------------------
-- This file is auto-generated by generate_vhdl_expected_values.py
-- DO NOT EDIT MANUALLY
----------------------------------------------------------------

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package qam_expected_pkg is
    -- Type definitions for LUT arrays
    type lut_array_16 is array (0 to 15) of signed(15 downto 0);
    type lut_array_64 is array (0 to 63) of signed(15 downto 0);
    type lut_array_128 is array (0 to 127) of signed(15 downto 0);
    type lut_array_256 is array (0 to 255) of signed(15 downto 0);

    -- Expected values for QAM-16
    constant EXPECTED_QAM_16_I : lut_array_16 := (
        0 => to_signed(-6144, 16),  -- -1.5
        1 => to_signed(-6144, 16),  -- -1.5
        2 => to_signed(-6144, 16),  -- -1.5
        3 => to_signed(-6144, 16),  -- -1.5
        4 => to_signed(-2048, 16),  -- -0.5
        5 => to_signed(-2048, 16),  -- -0.5
        6 => to_signed(-2048, 16),  -- -0.5
        7 => to_signed(-2048, 16),  -- -0.5
        8 => to_signed(2048, 16),   -- 0.5
        9 => to_signed(2048, 16),   -- 0.5
        10 => to_signed(2048, 16),  -- 0.5
        11 => to_signed(2048, 16),  -- 0.5
        12 => to_signed(6144, 16),  -- 1.5
        13 => to_signed(6144, 16),  -- 1.5
        14 => to_signed(6144, 16),  -- 1.5
        15 => to_signed(6144, 16),  -- 1.5
        others => (others => '0')
    );
    constant EXPECTED_QAM_16_Q : lut_array_16 := (
        0 => to_signed(-6144, 16),  -- -1.5
        1 => to_signed(-2048, 16),  -- -0.5
        2 => to_signed(2048, 16),   -- 0.5
        3 => to_signed(6144, 16),   -- 1.5
        4 => to_signed(-6144, 16),  -- -1.5
        5 => to_signed(-2048, 16),  -- -0.5
        6 => to_signed(2048, 16),   -- 0.5
        7 => to_signed(6144, 16),   -- 1.5
        8 => to_signed(-6144, 16),  -- -1.5
        9 => to_signed(-2048, 16),  -- -0.5
        10 => to_signed(2048, 16),  -- 0.5
        11 => to_signed(6144, 16),  -- 1.5
        12 => to_signed(-6144, 16), -- -1.5
        13 => to_signed(-2048, 16), -- -0.5
        14 => to_signed(2048, 16),  -- 0.5
        15 => to_signed(6144, 16),  -- 1.5
        others => (others => '0')
    );
    -- QAM-64, 128, 256の期待値は省略（スクリプトで生成）
end package qam_expected_pkg;

